-- liquibase formatted sql

-- changeset posadmin:V2000_create_data_product splitStatements:false
-- comment: Create business.data_product table (product catalog, without brand_fk/price/store columns added by later scripts)
DO
$$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables
                   WHERE table_schema = 'business' AND table_name = 'data_product') THEN

        CREATE TABLE business.data_product (
            id          INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            created_by  INTEGER,
            updated_by  INTEGER,
            created_at  TIMESTAMP(6) WITH TIME ZONE,
            updated_at  TIMESTAMP(6) WITH TIME ZONE,
            code        VARCHAR(255) NOT NULL,
            name        VARCHAR(255),
            min_stock   DOUBLE PRECISION,
            max_stock   DOUBLE PRECISION,
            CONSTRAINT data_product_pkey PRIMARY KEY (id),
            CONSTRAINT data_product_code_key UNIQUE (code),
            CONSTRAINT fk_data_product_created_by FOREIGN KEY (created_by)
                REFERENCES admin.admin_users(id) ON DELETE SET NULL,
            CONSTRAINT fk_data_product_updated_by FOREIGN KEY (updated_by)
                REFERENCES admin.admin_users(id) ON DELETE SET NULL
        );

        ALTER TABLE business.data_product OWNER TO posadmin;

        RAISE NOTICE 'Table business.data_product created successfully';
    ELSE
        RAISE NOTICE 'Table business.data_product already exists, skipping';
    END IF;
END
$$;
