apiVersion: v1
kind: Service
metadata:
  name: pos-admin-service
  namespace: pos-prod
spec:
  selector:
    app: pos-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
