apiVersion: v1
kind: Secret
metadata:
  name: pos-postgres-secret
  namespace: pos-prod
type: Opaque
data:
  # base64 of: jdbc:postgresql://<HOST>:5432/pos-db
  datasource-url: REPLACE_WITH_BASE64_ENCODED_JDBC_URL
  # base64 of: posadmin
  datasource-username: REPLACE_WITH_BASE64_ENCODED_USERNAME
  # base64 of: <db-password>
  datasource-password: REPLACE_WITH_BASE64_ENCODED_PASSWORD
