apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: app-dev
type: Opaque
stringData:
  AI_API_KEY: REPLACE_WITH_YOUR_GEMINI_API_KEY
  APP_RSA_PRIVATE_KEY: REPLACE_WITH_YOUR_RSA_PRIVATE_KEY
  JWT_SECRET: REPLACE_WITH_YOUR_JWT_SECRET
  COOKIE_SECURE: "true"
